#!/bin/bash

wallpapers=~/.wallpapers

set_collection () {
    collection=$1
    outdir=$wallpapers/$collection
    mkdir -p $outdir
}

set_collection nature
wget -nc -O $outdir/sduLRvf.jpeg https://i.imgur.com/sduLRvf.jpeg
wget -nc -O $outdir/tXtwrPd.jpeg https://i.imgur.com/tXtwrPd.jpeg
wget -nc -O $outdir/IVyU5Im.jpeg https://i.imgur.com/IVyU5Im.jpeg
wget -nc -O $outdir/QguApMA.jpeg https://i.imgur.com/QguApMA.jpeg
wget -nc -O $outdir/yxovJ4S.jpeg https://i.imgur.com/yxovJ4S.jpeg
wget -nc -O $outdir/fNXT1wc.jpeg https://i.imgur.com/fNXT1wc.jpeg
wget -nc -O $outdir/gjEZAJ7.jpeg https://i.imgur.com/gjEZAJ7.jpeg
wget -nc -O $outdir/JHHx0AD.jpeg https://i.imgur.com/JHHx0AD.jpeg
wget -nc -O $outdir/PnSeZX3.jpeg https://i.imgur.com/PnSeZX3.jpeg
wget -nc -O $outdir/IVefonq.jpeg https://i.imgur.com/IVefonq.jpeg
wget -nc -O $outdir/X92aA5Y.jpeg https://i.imgur.com/X92aA5Y.jpeg
wget -nc -O $outdir/Gb6xVGP.jpeg https://i.imgur.com/Gb6xVGP.jpeg
wget -nc -O $outdir/I3KJdGy.jpeg https://i.imgur.com/I3KJdGy.jpeg
wget -nc -O $outdir/fgfG6Hl.jpeg https://i.imgur.com/fgfG6Hl.jpeg
wget -nc -O $outdir/zlc7uSR.jpeg https://i.imgur.com/zlc7uSR.jpeg
wget -nc -O $outdir/PVU0dxc.jpeg https://i.imgur.com/PVU0dxc.jpeg
wget -nc -O $outdir/p53E302.jpeg https://i.imgur.com/p53E302.jpeg
wget -nc -O $outdir/OdjFda3.jpeg https://i.imgur.com/OdjFda3.jpeg
wget -nc -O $outdir/Pboz5mG.jpeg https://i.imgur.com/Pboz5mG.jpeg
wget -nc -O $outdir/c3hJOBE.jpeg https://i.imgur.com/c3hJOBE.jpeg
wget -nc -O $outdir/QO2wXxa.jpeg https://i.imgur.com/QO2wXxa.jpeg
wget -nc -O $outdir/QLJfdkH.jpeg https://i.imgur.com/QLJfdkH.jpeg
wget -nc -O $outdir/GqhO0RM.jpeg https://i.imgur.com/GqhO0RM.jpeg
wget -nc -O $outdir/TG87poQ.jpeg https://i.imgur.com/TG87poQ.jpeg
wget -nc -O $outdir/ivxdtnO.jpeg https://i.imgur.com/ivxdtnO.jpeg
wget -nc -O $outdir/0ic5msX.jpeg https://i.imgur.com/0ic5msX.jpeg
wget -nc -O $outdir/g2lgz0n.jpeg https://i.imgur.com/g2lgz0n.jpeg
wget -nc -O $outdir/EGgyVOq.jpeg https://i.imgur.com/EGgyVOq.jpeg
wget -nc -O $outdir/dNcRfqb.jpeg https://i.imgur.com/dNcRfqb.jpeg
wget -nc -O $outdir/FeawV44.jpeg https://i.imgur.com/FeawV44.jpeg
wget -nc -O $outdir/bCJxqkE.jpeg https://i.imgur.com/bCJxqkE.jpeg
wget -nc -O $outdir/c1YSqf0.jpeg https://i.imgur.com/c1YSqf0.jpeg
wget -nc -O $outdir/lmHsAqU.jpeg https://i.imgur.com/lmHsAqU.jpeg
wget -nc -O $outdir/uspc64E.jpeg https://i.imgur.com/uspc64E.jpeg
wget -nc -O $outdir/DGNgiv5.jpeg https://i.imgur.com/DGNgiv5.jpeg
wget -nc -O $outdir/OMuGvCj.jpeg https://i.imgur.com/OMuGvCj.jpeg
wget -nc -O $outdir/3kZpDVO.jpeg https://i.imgur.com/3kZpDVO.jpeg
wget -nc -O $outdir/4mL3UtW.jpeg https://i.imgur.com/4mL3UtW.jpeg
wget -nc -O $outdir/kA8ca1h.jpeg https://i.imgur.com/kA8ca1h.jpeg
wget -nc -O $outdir/KmtkDz2.jpeg https://i.imgur.com/KmtkDz2.jpeg
wget -nc -O $outdir/3JaOkVv.jpeg https://i.imgur.com/3JaOkVv.jpeg
wget -nc -O $outdir/0RCJwCT.jpeg https://i.imgur.com/0RCJwCT.jpeg
wget -nc -O $outdir/gWCHwKM.jpeg https://i.imgur.com/gWCHwKM.jpeg
wget -nc -O $outdir/7pY01Vl.png https://i.imgur.com/7pY01Vl.png
wget -nc -O $outdir/1ES3hPX.jpeg https://i.imgur.com/1ES3hPX.jpeg
wget -nc -O $outdir/3M2rek6.jpeg https://i.imgur.com/3M2rek6.jpeg
wget -nc -O $outdir/gfD7mMG.jpeg https://i.imgur.com/gfD7mMG.jpeg
wget -nc -O $outdir/7Kxx4LP.jpeg https://i.imgur.com/7Kxx4LP.jpeg
wget -nc -O $outdir/OHcyseE.jpeg https://i.imgur.com/OHcyseE.jpeg
wget -nc -O $outdir/ZrQcii7.jpeg https://i.imgur.com/ZrQcii7.jpeg
wget -nc -O $outdir/Wno68T7.jpeg https://i.imgur.com/Wno68T7.jpeg
wget -nc -O $outdir/Ow2gQFH.jpeg https://i.imgur.com/Ow2gQFH.jpeg
wget -nc -O $outdir/uIHa176.jpeg https://i.imgur.com/uIHa176.jpeg
wget -nc -O $outdir/9P54mou.jpeg https://i.imgur.com/9P54mou.jpeg
wget -nc -O $outdir/VEL80hT.jpeg https://i.imgur.com/VEL80hT.jpeg
wget -nc -O $outdir/VAG92vU.jpeg https://i.imgur.com/VAG92vU.jpeg
wget -nc -O $outdir/8pbvlmp.jpeg https://i.imgur.com/8pbvlmp.jpeg
wget -nc -O $outdir/pZfnmqf.jpeg https://i.imgur.com/pZfnmqf.jpeg
wget -nc -O $outdir/GZvvrFy.jpeg https://i.imgur.com/GZvvrFy.jpeg
wget -nc -O $outdir/rox4ye6.jpeg https://i.imgur.com/rox4ye6.jpeg
wget -nc -O $outdir/3vyjdZz.jpeg https://i.imgur.com/3vyjdZz.jpeg
wget -nc -O $outdir/ovOgQpN.jpeg https://i.imgur.com/ovOgQpN.jpeg
wget -nc -O $outdir/9y185KI.jpeg https://i.imgur.com/9y185KI.jpeg
wget -nc -O $outdir/7omqS0U.jpeg https://i.imgur.com/7omqS0U.jpeg
wget -nc -O $outdir/1mRl1nx.jpeg https://i.imgur.com/1mRl1nx.jpeg
wget -nc -O $outdir/dqCEoaB.jpeg https://i.imgur.com/dqCEoaB.jpeg
wget -nc -O $outdir/knPRmvA.jpeg https://i.imgur.com/knPRmvA.jpeg
wget -nc -O $outdir/0lSLfdI.jpeg https://i.imgur.com/0lSLfdI.jpeg
wget -nc -O $outdir/8I5IbpP.jpeg https://i.imgur.com/8I5IbpP.jpeg
wget -nc -O $outdir/f3GVoDb.jpeg https://i.imgur.com/f3GVoDb.jpeg
wget -nc -O $outdir/jG7Emga.jpeg https://i.imgur.com/jG7Emga.jpeg
wget -nc -O $outdir/y25BotJ.jpeg https://i.imgur.com/y25BotJ.jpeg
wget -nc -O $outdir/Wwzp07R.jpeg https://i.imgur.com/Wwzp07R.jpeg
wget -nc -O $outdir/qSrMh5U.jpeg https://i.imgur.com/qSrMh5U.jpeg
wget -nc -O $outdir/WtMFngV.jpeg https://i.imgur.com/WtMFngV.jpeg
wget -nc -O $outdir/zmhQcdK.jpeg https://i.imgur.com/zmhQcdK.jpeg
wget -nc -O $outdir/Mx7lcuL.jpeg https://i.imgur.com/Mx7lcuL.jpeg
wget -nc -O $outdir/n9QlyUY.jpeg https://i.imgur.com/n9QlyUY.jpeg
wget -nc -O $outdir/za7L69m.jpeg https://i.imgur.com/za7L69m.jpeg
wget -nc -O $outdir/HcA8253.jpeg https://i.imgur.com/HcA8253.jpeg
wget -nc -O $outdir/Gg4dbg5.jpeg https://i.imgur.com/Gg4dbg5.jpeg
wget -nc -O $outdir/XsyuyBX.jpeg https://i.imgur.com/XsyuyBX.jpeg
wget -nc -O $outdir/QIAB4VU.jpeg https://i.imgur.com/QIAB4VU.jpeg
wget -nc -O $outdir/OVr1Jyv.jpeg https://i.imgur.com/OVr1Jyv.jpeg
wget -nc -O $outdir/L8R7FgT.jpeg https://i.imgur.com/L8R7FgT.jpeg
wget -nc -O $outdir/8Be6Kmh.jpeg https://i.imgur.com/8Be6Kmh.jpeg
wget -nc -O $outdir/kuXgVGg.jpeg https://i.imgur.com/kuXgVGg.jpeg
wget -nc -O $outdir/Nu1FuSh.jpeg https://i.imgur.com/Nu1FuSh.jpeg
wget -nc -O $outdir/57118Db.jpeg https://i.imgur.com/57118Db.jpeg
wget -nc -O $outdir/NzZhsn5.jpeg https://i.imgur.com/NzZhsn5.jpeg
wget -nc -O $outdir/EQ2Y17s.jpeg https://i.imgur.com/EQ2Y17s.jpeg
wget -nc -O $outdir/ZHzash8.jpeg https://i.imgur.com/ZHzash8.jpeg
wget -nc -O $outdir/LquRPSZ.jpeg https://i.imgur.com/LquRPSZ.jpeg
wget -nc -O $outdir/ZOn0xR0.jpeg https://i.imgur.com/ZOn0xR0.jpeg
wget -nc -O $outdir/eSDlrID.jpeg https://i.imgur.com/eSDlrID.jpeg
wget -nc -O $outdir/L6WX4QX.jpeg https://i.imgur.com/L6WX4QX.jpeg
wget -nc -O $outdir/u27oejP.jpeg https://i.imgur.com/u27oejP.jpeg
wget -nc -O $outdir/CX1g1jT.jpeg https://i.imgur.com/CX1g1jT.jpeg
wget -nc -O $outdir/iiXsmnL.jpeg https://i.imgur.com/iiXsmnL.jpeg
wget -nc -O $outdir/mEjst5b.jpeg https://i.imgur.com/mEjst5b.jpeg
wget -nc -O $outdir/nxkGy0q.jpeg https://i.imgur.com/nxkGy0q.jpeg
wget -nc -O $outdir/1BDbhzP.jpeg https://i.imgur.com/1BDbhzP.jpeg
wget -nc -O $outdir/zz9fSw9.jpeg https://i.imgur.com/zz9fSw9.jpeg
wget -nc -O $outdir/vKAsa8Y.jpeg https://i.imgur.com/vKAsa8Y.jpeg
wget -nc -O $outdir/Swt89YB.jpeg https://i.imgur.com/Swt89YB.jpeg
wget -nc -O $outdir/q2tyKoX.jpeg https://i.imgur.com/q2tyKoX.jpeg
wget -nc -O $outdir/OIDTMve.jpeg https://i.imgur.com/OIDTMve.jpeg
wget -nc -O $outdir/HPntFwO.jpeg https://i.imgur.com/HPntFwO.jpeg
wget -nc -O $outdir/7A6UpSi.jpeg https://i.imgur.com/7A6UpSi.jpeg
wget -nc -O $outdir/M0XCF6i.jpeg https://i.imgur.com/M0XCF6i.jpeg
wget -nc -O $outdir/GjJmgcl.jpeg https://i.imgur.com/GjJmgcl.jpeg
wget -nc -O $outdir/BpmvNf0.jpeg https://i.imgur.com/BpmvNf0.jpeg
wget -nc -O $outdir/vi2lTKR.jpeg https://i.imgur.com/vi2lTKR.jpeg
wget -nc -O $outdir/yNGFKlK.jpeg https://i.imgur.com/yNGFKlK.jpeg
wget -nc -O $outdir/j19Gqdg.jpeg https://i.imgur.com/j19Gqdg.jpeg
wget -nc -O $outdir/kjBRZr5.jpeg https://i.imgur.com/kjBRZr5.jpeg
wget -nc -O $outdir/2NwRsVZ.jpeg https://i.imgur.com/2NwRsVZ.jpeg
wget -nc -O $outdir/CLBdlr6.jpeg https://i.imgur.com/CLBdlr6.jpeg
wget -nc -O $outdir/WLGQQRQ.jpeg https://i.imgur.com/WLGQQRQ.jpeg
wget -nc -O $outdir/3eLE5lV.jpeg https://i.imgur.com/3eLE5lV.jpeg
wget -nc -O $outdir/PnEgOSL.jpeg https://i.imgur.com/PnEgOSL.jpeg
wget -nc -O $outdir/I1Dr1P7.jpeg https://i.imgur.com/I1Dr1P7.jpeg
wget -nc -O $outdir/vJyBmL3.jpeg https://i.imgur.com/vJyBmL3.jpeg
wget -nc -O $outdir/TwhsROW.jpeg https://i.imgur.com/TwhsROW.jpeg
wget -nc -O $outdir/wMgQ8FP.jpeg https://i.imgur.com/wMgQ8FP.jpeg
wget -nc -O $outdir/SjSUnFs.jpeg https://i.imgur.com/SjSUnFs.jpeg
wget -nc -O $outdir/C8Ev0zM.jpeg https://i.imgur.com/C8Ev0zM.jpeg
wget -nc -O $outdir/b9uaoaZ.jpeg https://i.imgur.com/b9uaoaZ.jpeg
wget -nc -O $outdir/lI2sNqx.jpeg https://i.imgur.com/lI2sNqx.jpeg
wget -nc -O $outdir/zzZcQyF.jpeg https://i.imgur.com/zzZcQyF.jpeg
wget -nc -O $outdir/OVXD3on.jpeg https://i.imgur.com/OVXD3on.jpeg
wget -nc -O $outdir/65xoCiE.jpeg https://i.imgur.com/65xoCiE.jpeg
wget -nc -O $outdir/csxi2rG.jpeg https://i.imgur.com/csxi2rG.jpeg
wget -nc -O $outdir/d4eJWao.jpeg https://i.imgur.com/d4eJWao.jpeg
wget -nc -O $outdir/4i8XHrC.jpeg https://i.imgur.com/4i8XHrC.jpeg
wget -nc -O $outdir/ITf9HcE.jpeg https://i.imgur.com/ITf9HcE.jpeg
wget -nc -O $outdir/kVCqpbV.jpeg https://i.imgur.com/kVCqpbV.jpeg
wget -nc -O $outdir/sMtv49j.jpeg https://i.imgur.com/sMtv49j.jpeg
wget -nc -O $outdir/sN6N1LC.jpeg https://i.imgur.com/sN6N1LC.jpeg
wget -nc -O $outdir/1cs0yj1.jpeg https://i.imgur.com/1cs0yj1.jpeg
wget -nc -O $outdir/pwv30UB.jpeg https://i.imgur.com/pwv30UB.jpeg
wget -nc -O $outdir/6UR9Dyv.jpeg https://i.imgur.com/6UR9Dyv.jpeg
wget -nc -O $outdir/P75FOZX.jpeg https://i.imgur.com/P75FOZX.jpeg
wget -nc -O $outdir/pzMJg1I.jpeg https://i.imgur.com/pzMJg1I.jpeg
wget -nc -O $outdir/wG8FJKm.jpeg https://i.imgur.com/wG8FJKm.jpeg
wget -nc -O $outdir/2awMekY.jpeg https://i.imgur.com/2awMekY.jpeg
wget -nc -O $outdir/ScBB1Ho.jpeg https://i.imgur.com/ScBB1Ho.jpeg
wget -nc -O $outdir/QxQbKT2.jpeg https://i.imgur.com/QxQbKT2.jpeg

set_collection space
wget -nc -O $outdir/OeEfSfO.jpeg https://i.imgur.com/OeEfSfO.jpeg 
wget -nc -O $outdir/OeEfSfO.jpeg https://i.imgur.com/OeEfSfO.jpeg 
wget -nc -O $outdir/Q1zLbmZ.jpeg https://i.imgur.com/Q1zLbmZ.jpeg 
wget -nc -O $outdir/GOniPl0.jpeg https://i.imgur.com/GOniPl0.jpeg 
wget -nc -O $outdir/gjPQaoW.jpeg https://i.imgur.com/gjPQaoW.jpeg 
wget -nc -O $outdir/NDLV2dp.jpeg https://i.imgur.com/NDLV2dp.jpeg 
wget -nc -O $outdir/myX9Q4f.jpeg https://i.imgur.com/myX9Q4f.jpeg 
wget -nc -O $outdir/s01CNmS.jpeg https://i.imgur.com/s01CNmS.jpeg 
wget -nc -O $outdir/CcqtfAH.jpeg https://i.imgur.com/CcqtfAH.jpeg 
wget -nc -O $outdir/20MZU0Z.jpeg https://i.imgur.com/20MZU0Z.jpeg 
wget -nc -O $outdir/JS7Tf9B.jpeg https://i.imgur.com/JS7Tf9B.jpeg 
wget -nc -O $outdir/xWNQjRU.jpeg https://i.imgur.com/xWNQjRU.jpeg 
wget -nc -O $outdir/Qg3C7zR.jpeg https://i.imgur.com/Qg3C7zR.jpeg 
wget -nc -O $outdir/IuPKMzc.jpeg https://i.imgur.com/IuPKMzc.jpeg 
wget -nc -O $outdir/lfXNLKA.jpeg https://i.imgur.com/lfXNLKA.jpeg 
wget -nc -O $outdir/YfUFrWF.jpeg https://i.imgur.com/YfUFrWF.jpeg 
wget -nc -O $outdir/BDeaofO.jpeg https://i.imgur.com/BDeaofO.jpeg 
wget -nc -O $outdir/Xc1EHww.jpeg https://i.imgur.com/Xc1EHww.jpeg 
wget -nc -O $outdir/eFnnOMC.jpeg https://i.imgur.com/eFnnOMC.jpeg 
wget -nc -O $outdir/dqtZCgN.jpeg https://i.imgur.com/dqtZCgN.jpeg 
wget -nc -O $outdir/1QgGnSs.jpeg https://i.imgur.com/1QgGnSs.jpeg 
wget -nc -O $outdir/HKPMJBD.jpeg https://i.imgur.com/HKPMJBD.jpeg 
wget -nc -O $outdir/WrPQcoH.jpeg https://i.imgur.com/WrPQcoH.jpeg 
wget -nc -O $outdir/kfZud2w.jpeg https://i.imgur.com/kfZud2w.jpeg 
wget -nc -O $outdir/g8MGeRI.jpeg https://i.imgur.com/g8MGeRI.jpeg 
wget -nc -O $outdir/sNXbewV.jpeg https://i.imgur.com/sNXbewV.jpeg 
wget -nc -O $outdir/i7k6wbK.jpeg https://i.imgur.com/i7k6wbK.jpeg 
wget -nc -O $outdir/TA6Jz4d.jpeg https://i.imgur.com/TA6Jz4d.jpeg 
wget -nc -O $outdir/qqwAxPh.jpeg https://i.imgur.com/qqwAxPh.jpeg 
wget -nc -O $outdir/Po13au9.jpeg https://i.imgur.com/Po13au9.jpeg 
wget -nc -O $outdir/ppN1z7a.jpeg https://i.imgur.com/ppN1z7a.jpeg 
wget -nc -O $outdir/Rv1Bu2y.jpeg https://i.imgur.com/Rv1Bu2y.jpeg 
wget -nc -O $outdir/Cxvsgk9.jpeg https://i.imgur.com/Cxvsgk9.jpeg 
wget -nc -O $outdir/TAwlQQR.jpeg https://i.imgur.com/TAwlQQR.jpeg 
wget -nc -O $outdir/AMwf5nn.jpeg https://i.imgur.com/AMwf5nn.jpeg 
wget -nc -O $outdir/l7L39vG.jpeg https://i.imgur.com/l7L39vG.jpeg 
wget -nc -O $outdir/pSd2rUC.jpeg https://i.imgur.com/pSd2rUC.jpeg 
wget -nc -O $outdir/JpJujTb.jpeg https://i.imgur.com/JpJujTb.jpeg 
wget -nc -O $outdir/c1vhYXC.png https://i.imgur.com/c1vhYXC.png 
wget -nc -O $outdir/tEztBlR.png https://i.imgur.com/tEztBlR.png 
wget -nc -O $outdir/QefAMZO.png https://i.imgur.com/QefAMZO.png 
wget -nc -O $outdir/WIqXbrl.png https://i.imgur.com/WIqXbrl.png 
wget -nc -O $outdir/7e158X1.png https://i.imgur.com/7e158X1.png 
wget -nc -O $outdir/aSanRPt.jpeg https://i.imgur.com/aSanRPt.jpeg 
wget -nc -O $outdir/8pWnCKj.jpeg https://i.imgur.com/8pWnCKj.jpeg 
wget -nc -O $outdir/WhA5MFA.jpeg https://i.imgur.com/WhA5MFA.jpeg 
wget -nc -O $outdir/MNt8dDh.jpeg https://i.imgur.com/MNt8dDh.jpeg 
wget -nc -O $outdir/qz6sF0q.jpeg https://i.imgur.com/qz6sF0q.jpeg 
wget -nc -O $outdir/30a95LY.jpeg https://i.imgur.com/30a95LY.jpeg 
wget -nc -O $outdir/Rpq9Mee.jpeg https://i.imgur.com/Rpq9Mee.jpeg 
wget -nc -O $outdir/fj7dQKM.jpeg https://i.imgur.com/fj7dQKM.jpeg 
wget -nc -O $outdir/vWVhN2V.jpeg https://i.imgur.com/vWVhN2V.jpeg 
wget -nc -O $outdir/eViLl6L.jpeg https://i.imgur.com/eViLl6L.jpeg 
